scrape_configs:
  - job_name: 'scylla'
    static_configs:
      - targets: ['scylladb1:9180', 'scylladb2:9180']
      
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']