version: '3'


networks:
  scylla_net:
    name: scylla_net
    driver: bridge
  cassandra: 
    driver: bridge

services:
  scylladb1:
    image: scylladb/scylla:latest
    container_name: scylladb1
    ports:
      - "9042:9042"
      - "9180:9180"
    volumes:
      - scylladb_data1:/var/lib/scylla
    command: --seeds=scylladb1,scylladb2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    environment:
      - SCYLLA_USERNAME=scylla_user
      - SCYLLA_PASSWORD=scylla_pass
    networks:
      scylla_net:

  scylladb2:
    image: scylladb/scylla:latest
    container_name: scylladb2
    ports:
      - "9045:9042"
      - "9181:9180"
    volumes:
      - scylladb_data2:/var/lib/scylla
    command: --seeds=scylladb1,scylladb2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    environment:
      - SCYLLA_USERNAME=scylla_user
      - SCYLLA_PASSWORD=scylla_pass
    depends_on:
      - scylladb1
    networks:
      scylla_net:

  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9043:9042"
    volumes:
      - cassandra_data1:/var/lib/cassandra
    environment:
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZER=CassandraAuthorizer
      - CASSANDRA_PASSWORD_AUTHENTICATOR_ENABLED=true
      - CASSANDRA_SEEDS=cassandra1,cassandra2
    networks:
      - cassandra
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    ports:
      - "9044:9042"
    volumes:
      - cassandra_data2:/var/lib/cassandra
    environment:
      - HEAP_NEWSIZE=256M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZER=CassandraAuthorizer
      - CASSANDRA_PASSWORD_AUTHENTICATOR_ENABLED=true
      - CASSANDRA_SEEDS=cassandra1,cassandra2
    networks:
      - cassandra
    depends_on:
      - cassandra1
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

volumes:
  scylladb_data1:
  scylladb_data2:
  cassandra_data1:
  cassandra_data2:
